package views;

import model.ActiveObject;
import model.ActiveObjectThread;
import utils.SizeHelper;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by pkhvoros on 3/18/15.
 */
public class ActiveObjectViewController {
    private ActiveObject activeObject;
    private JLabel activeObjectId;
    private JPanel aoPanel;
    private JPanel threadsContainer;
    private List<ThreadViewController> threadViewControllers = new ArrayList<>();

    public ActiveObjectViewController(ActiveObject activeObject) {
        this.activeObject = activeObject;
        activeObjectId.setText(activeObject.getIdentifier());
        for (ActiveObjectThread activeObjectThread : activeObject.getThreads()) {
            ThreadViewController controller = new ThreadViewController(activeObjectThread);
            threadViewControllers.add(controller);
            threadsContainer.setSize(3000, 100);
        }
    }

    public JPanel getPanel() {
        return aoPanel;
    }

    public void update(SizeHelper sizeHelper) {
        for (ThreadViewController threadViewController : threadViewControllers) {
            threadViewController.drawThread(sizeHelper);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        aoPanel = new JPanel();
        aoPanel.setLayout(new BorderLayout(0, 0));
        aoPanel.setMaximumSize(new Dimension(300, 300));
        aoPanel.setMinimumSize(new Dimension(300, 300));
        activeObjectId = new JLabel();
        activeObjectId.setMaximumSize(new Dimension(-1, -1));
        activeObjectId.setMinimumSize(new Dimension(36, 100));
        activeObjectId.setText("Label");
        aoPanel.add(activeObjectId, BorderLayout.WEST);
        threadsContainer = new JPanel();
        threadsContainer.setLayout(new GridBagLayout());
        aoPanel.add(threadsContainer, BorderLayout.CENTER);
        threadsContainer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return aoPanel;
    }
}
